{{- if .Values.openshiftRoute }}
kind: Route
apiVersion: route.openshift.io/v1
metadata:
  annotations:
  labels:
    {{- include "nginx.labels" . | nindent 4 }}
  name: {{ include "nginx.fullname" . }}
spec:
  path: /
  to:
    kind: Service
    name: {{ include "nginx.fullname" . }}
    weight: 100
  wildcardPolicy: None
  tls:
    termination: edge
    insecureEdgeTerminationPolicy: Redirect
  wildcardPolicy: None
{{- end }}
