apiVersion: v2
name: zeoserver
description: ZEO Server for Plone

type: application

version: 0.1.0

appVersion: "5.3.0"

maintainers:
- name: Plone Foundation
  url: https://plone.org
sources:
- https://github.com/plone/helm-charts/
