# Default values for zeo.
replicaCount: 1

image:
  repository: plone/plone-zeo
  pullPolicy: IfNotPresent
  # Overrides the image tag whose default is the chart appVersion.
  tag: ""

imagePullSecrets: []
nameOverride: ""
fullnameOverride: ""

podAnnotations: {}

podSecurityContext: {}
  # fsGroup: 2000

securityContext: {}
  # capabilities:
  #   drop:
  #   - ALL
  # readOnlyRootFilesystem: true
  # runAsNonRoot: true
  # runAsUser: 1000

service:
  type: ClusterIP
  port: 8100

resources:
  requests:
    cpu: 50m
    memory: 48Mi
# limits:
#   cpu: 50m
#   memory: 48Mi

# if you are using the official plone docker images, all environment
# variables documented in the following URL are supported
# https://6.docs.plone.org/install/containers/images/zeo.html
# env:
#   - name: FOOBAR
#     value: "123"

persistence:
  enabled: true
  # storageClass: ""
  accessMode: ReadWriteOnce
  size: 5Gi

nodeSelector: {}

tolerations: []

affinity: {}
