# Default values for postgresql.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

image:
  repository: postgres
  pullPolicy: IfNotPresent
  # Overrides the image tag whose default is the chart appVersion.
  tag: ""

imagePullSecrets: []
nameOverride: ""
fullnameOverride: ""

# XXX We want to import this key in other charts, but import-values currently doesn't work with
# single values, see https://github.com/helm/helm/issues/2746. There is a chance we can simplify this
# once https://github.com/helm/helm/pull/9818 is merged.
dbsecret:
  name: plonedb

podAnnotations: {}
podLabels: {}

podSecurityContext: {}
  # fsGroup: 2000

securityContext: {}
  # capabilities:
  #   drop:
  #   - ALL
  # readOnlyRootFilesystem: true
  # runAsNonRoot: true
  # runAsUser: 1000

service:
  type: ClusterIP
  protocol: TCP
  port: 5432

resources: {}
  # We usually recommend not to specify default resources and to leave this as a conscious
  # choice for the user. This also increases chances charts run on environments with little
  # resources, such as Minikube. If you do want to specify resources, uncomment the following
  # lines, adjust them as necessary, and remove the curly braces after 'resources:'.
  # limits:
  #   cpu: 100m
  #   memory: 128Mi
  # requests:
  #   cpu: 100m
  #   memory: 128Mi

# Additional volumes on the output Deployment definition.
volumes:
  - name: data
    persistentVolumeClaim:
      claimName: db-pvc

# Additional volumeMounts on the output Deployment definition.
volumeMounts:
  - mountPath: /var/lib/postgresql/data
    name: data

nodeSelector: {}

tolerations: []

affinity: {}
