{{- if .Values.ingress.enabled -}}
{{- $fullName := include "plone.fullname" . -}}
{{- $hostName := (index .Values.ingress.hosts 0).host -}}
{{- $svcPort := .Values.backend.service.port -}}
{{- if and .Values.ingress.className (not (semverCompare ">=1.18-0" .Capabilities.KubeVersion.GitVersion)) }}
  {{- if not (hasKey .Values.ingress.annotations "kubernetes.io/ingress.class") }}
  {{- $_ := set .Values.ingress.annotations "kubernetes.io/ingress.class" .Values.ingress.className}}
  {{- end }}
{{- end }}
{{- if semverCompare ">=1.19-0" .Capabilities.KubeVersion.GitVersion -}}
apiVersion: networking.k8s.io/v1
{{- else if semverCompare ">=1.14-0" .Capabilities.KubeVersion.GitVersion -}}
apiVersion: networking.k8s.io/v1beta1
{{- else -}}
apiVersion: extensions/v1beta1
{{- end }}
kind: Ingress
metadata:
  name: {{ $fullName }}-api
  labels:
    {{- include "plone.labels" . | nindent 4 }}
  {{- with .Values.apiIngress.annotations }}
  annotations:
    {{- if contains "nginx" .Values.ingress.class }}
    nginx.ingress.kubernetes.io/use-regex: "true"
      {{- if .Values.ingress.tls }}
    nginx.ingress.kubernetes.io/rewrite-target: "/VirtualHostBase/https/{{ $hostName }}:443/Plone/++api++/VirtualHostRoot/$2"
      {{- else }}
    nginx.ingress.kubernetes.io/rewrite-target: "/VirtualHostBase/http/{{ $hostName }}:80/Plone/++api++/VirtualHostRoot/$2"
      {{- end }}
    nginx.ingress.kubernetes.io/service-upstream: "true"
    {{- end }}
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  {{- if and .Values.ingress.className (semverCompare ">=1.18-0" .Capabilities.KubeVersion.GitVersion) }}
  ingressClassName: {{ .Values.ingress.className }}
  {{- end }}
  {{- if .Values.ingress.tls }}
  tls:
    {{- range .Values.ingress.tls }}
    - hosts:
        {{- range .hosts }}
        - {{ . | quote }}
        {{- end }}
      secretName: {{ .secretName }}
    {{- end }}
  {{- end }}
  rules:
    - host: {{ $hostName }}
      http:
        paths:
          - path: /\+\+api\+\+($|/.*)
            {{- if semverCompare ">=1.18-0" $.Capabilities.KubeVersion.GitVersion }}
            pathType: ImplementationSpecific
            {{- end }}
            backend:
              {{- if semverCompare ">=1.19-0" $.Capabilities.KubeVersion.GitVersion }}
              service:
                name: {{ $fullName }}-backend
                port:
                  number: {{ $svcPort }}
              {{- else }}
              serviceName: {{ $fullName }}-backend
              servicePort: {{ $svcPort }}
              {{- end }}
{{- end }}
