kind: ConfigMap
apiVersion: v1
metadata:
  name: {{ include "backend.fullname" . }}
  labels:
    {{- include "backend.labels" . | nindent 4 }}
data:
  default.vcl: |-
    vcl 4.1;

    backend default {
      .host = "{{ .Release.Name }}-backend";
      .port = "8080";
    }
