apiVersion: v1
kind: Service
metadata:
  name: {{ include "zeo.fullname" . }}
  labels:
    {{- include "zeo.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: 8100
      protocol: TCP
      name: zeo
  selector:
    {{- include "zeo.selectorLabels" . | nindent 4 }}
