# Default values for plone backend
backend:
  image:
    repository: plone/plone-backend
    pullPolicy: IfNotPresent
    # Overrides the image tag whose default is the chart appVersion.
    tag: ""
  replicaCount: 1
  podDisruptionBudget:
    enabled: true
    minAvailable: 50%
    # maxUnavailable:
  service:
    type: ClusterIP
    port: 8080
  resources:
    requests:
      cpu: 100m
      memory: 280Mi
  # limits:
  #   cpu: 100m
  #   memory: 128Mi

  # if you are using the official plone docker images, all environment
  # variables documented in the following URL are supported
  # https://6.docs.plone.org/install/containers/images/backend.html
  # env:
  #   - name: FOOBAR
  #     value: abc

  podAnnotations: {}
  podSecurityContext: {}
  #  fsGroup: 2000
  securityContext: {}
  #  capabilities:
  #    drop:
  #    - ALL
  #    readOnlyRootFilesystem: true
  #   runAsNonRoot: true
  #   runAsUser: 999
  nodeSelector: {}
  tolerations: []
  affinity: {}

# Default values for plone frontend
frontend:
  image:
    repository: plone/plone-frontend
    pullPolicy: IfNotPresent
    tag: "16.21.2"
  replicaCount: 1
  podDisruptionBudget:
    enabled: true
    minAvailable: 50%
    # maxUnavailable:
  service:
    type: ClusterIP
    port: 3000
  resources:
    requests:
      cpu: 50m
      memory: 192Mi
  # limits:
  #   cpu: 100m
  #   memory: 128Mi

  # if you are using the official plone docker images, all environment
  # variables documented in the following URL are supported
  # https://6.docs.plone.org/install/containers/images/frontend.html
  # env:
  #   - name: FOOBAR
  #     value: xyz

  podAnnotations: {}
  podSecurityContext: {}
  #  fsGroup: 2000
  securityContext: {}
  #  capabilities:
  #    drop:
  #    - ALL
  #    readOnlyRootFilesystem: true
  #   runAsNonRoot: true
  #   runAsUser: 999
  nodeSelector: {}
  tolerations: []
  affinity: {}

imagePullSecrets: []
nameOverride: ""
fullnameOverride: ""

ingress:
  enabled: false
  className: ""
  annotations:
    # cert-manager.io/cluster-issuer: "letsencrypt-prod"
  hosts:
    - host: chart-example.local
      paths:
        - path: /
          pathType: ImplementationSpecific
  tls: []
  #  - secretName: chart-example-tls
  #    hosts:
  #      - chart-example.local

apiIngress:
  enabled: false
  annotations:
    # cert-manager.io/cluster-issuer: "letsencrypt-prod"

# Default settings for zeoserver
zeoserver:
  enabled: true
  persistence:
    enabled: true