# This GitHub Actions workflow lints and tests Helm charts on pull requests and pushes to the repository.
name: Lint and Test Charts

on: [pull_request, push]

env:
  CHARTS_TO_CHECK: backend frontend nginx postgres varnish zeoserver plone6-classic-nodb plone6-classic-pg plone6-volto-pg plone6-volto-pg-nginx-varnish plone6-volto-zeo

jobs:
  lint-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up Helm
        uses: azure/setup-helm@v4

      - uses: actions/setup-python@v5
        with:
          python-version: '3.12'
          check-latest: true

      - name: Set up chart-testing
        uses: helm/chart-testing-action@v2

      - name: Run chart-testing (list-changed)
        id: list-changed
        run: |
          # List the changed charts on the target branch and set the 'changed' output to 'true' if there are any changes.
          CHARTDIRS=$(for chartdir in $CHARTS_TO_CHECK; do echo -n "--chart-dirs ./${chartdir} "; done)
          echo $CHARTDIRS
          changed=$(ct list-changed --target-branch ${{ github.event.repository.default_branch }} $CHARTDIRS )
          if [[ -n "$changed" ]]; then
            echo "changed=true" >> "$GITHUB_OUTPUT"
          fi

      - name: Run chart-testing (lint)
        if: steps.list-changed.outputs.changed == 'true'
        run: ct lint --target-branch ${{ github.event.repository.default_branch }} $CHARTDIRS

      - name: Create kind cluster
        if: steps.list-changed.outputs.changed == 'true'
        uses: helm/kind-action@v1

      - name: Run chart-testing (install)
        if: steps.list-changed.outputs.changed == 'true'
        run: ct install --target-branch ${{ github.event.repository.default_branch }} $CHARTDIRS
